### ISSUE TITLE
Serverless Mixtral Runpod

### ISSUE THREAD

**Issue by anujnayyar1** [TrelisResearch/one-click-llms#3]
Any chance you could turn this template into a serverless one akin to:
https://github.com/runpod-workers/worker-tgi

**Comment by RonanKMcGovern** [comment]
Yeah, thanks for the suggestion, it's on my list of vids. Let me target that soon.

**Comment by RonanKMcGovern** [comment]
Howdy, so I'm in touch with Runpod about supporting serverless templates again.

In the meantime, I've just released [this explainer video](https://youtu.be/_5uM6UDOxOA).
