### ISSUE TITLE
Llama cpp compilation error, runpod

### ISSUE THREAD

**Issue by usatenko** [TrelisResearch/one-click-llms#7]
When I try this docker in RunPod I see that the llamacpp can't be compiled due to this error.
Makefile:77: *** LLAMA_CUBLAS is removed. Use GGML_CUDA instead..  Stop.

Can it be fixed?

RunPod template is "Mistral Instruct v0.1 Llama.cpp Server by Trelis"

**Comment by RonanKMcGovern** [comment]
Thanks, I probably need to update the docker image.

In the meantime, can you just run with a vLLM server instead? (it will be faster)

Is there a particular reason you want to use the llama.ccp ? Cheers

**Comment by usatenko** [comment]
yes, the new mistral nemo is out and I have not found any quantized versions of it to run on vllm, this is why I am trying to run gguf one.
As far as I see vllm can't run gguf model. Maybe I am missing something.

**Comment by RonanKMcGovern** [comment]
Howdy again, ok, a few updates:

1. I've fixed the llama.cpp docker image. Wow there were tons of breaking changes. Took a few hours. This works for Mistral 7B.

2. Unfortunately I can't get Mistral Nemo GGUF to work, I tried out a few of the top repos. There's a one-click template now in this repo, and you can try it out maybe subbing in some other repo - but it just seems the tokenizer and model aren't supported yet.

Really the best way to do this is vllm (which works if you build from source). I've added a template to the one-click, once they update the latest vllm docker image.

TGI will probably also come soon this week.

**Comment by usatenko** [comment]
Thank you very much for attention to the issue.
I will try it and let you know.

**Comment by usatenko** [comment]
Same issue, mistral 7b works, mistral nemo fails with segmentation fault. I will try to find a solution.
Anyway, thank you for the help.

**Comment by usatenko** [comment]
it looks like that the new tokenizer "tekken" is not fully supported by llamacpp, this is the reason why it crashes

**Comment by RonanKMcGovern** [comment]
yeah exactly, hopefully soon this week this might get fixed

**Comment by RonanKMcGovern** [comment]
Closing this off, I'll open a new issue for Nemo

**Comment by usatenko** [comment]
I think it is opened already: https://github.com/ggerganov/llama.cpp/issues/8577

> Closing this off, I'll open a new issue for Nemo
